"""add foreign key to speaker

Revision ID: be9c651ad094
Revises: 96c55e4f67f3
Create Date: 2024-01-17 16:13:40.862896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9c651ad094'
down_revision = '96c55e4f67f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_speakers_activity_id_activities'), 'activities', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_speakers_activity_id_activities'), type_='foreignkey')
        batch_op.drop_column('activity_id')

    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
